	  <link href="bower_components/select2/dist/css/select2.min.css" rel="stylesheet">
      <link href="bower_components/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
      <link href="bower_components/dropzone/dist/dropzone.css" rel="stylesheet">
      <link href="bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
      <link href="bower_components/fullcalendar/dist/fullcalendar.min.css" rel="stylesheet">
      <link href="bower_components/perfect-scrollbar/css/perfect-scrollbar.min.css" rel="stylesheet">
      <link href="bower_components/slick-carousel/slick/slick.css" rel="stylesheet">
      <link href="icon_fonts_assets/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">
      <link href="css/main-version=4.5.0.css" rel="stylesheet">
      <link href="icon_fonts_assets/font-awesome/css/font-awesome.min.css" rel="stylesheet">